"use client";

import React from "react";
import Link from "next/link";
import { Brain, Sparkles, TrendingUp, AlertTriangle, ArrowRight, ShieldCheck } from "lucide-react";
import { useApp } from "@/lib/app-context";
import { AIAnalysisPanel } from "@/components/match/ai-analysis-panel";
import { WinProbabilityChart } from "@/components/match/win-probability-chart";

export default function GlobalAnalysisPage() {
  const { liveMatch } = useApp();

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-6">
      
      {/* Header */}
      <div className="border-b border-slate-800 pb-6">
        <div className="flex items-center gap-2 text-xs text-cyan-400 font-semibold mb-1">
          <Brain className="w-4 h-4" />
          <span>Predictive Modeling & Tactical Diagnostics</span>
        </div>
        <h1 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
          AI CRICKET MATCH ANALYSIS
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Phase diagnostics, live win-probability models, batter dominance momentum meters, and statistical projections.
        </p>
      </div>

      {/* Mandatory Disclaimer Box */}
      <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 flex items-start gap-3 text-xs text-slate-400">
        <ShieldCheck className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
        <div>
          <strong className="text-white">Analytical Integrity Notice:</strong> All probability estimates, momentum indicators, and projected scores are generated by algorithmic historical models based on live match states. Model outputs are strictly informational and not guaranteed outcomes.
        </div>
      </div>

      {/* Active Live Match Spotlight Analysis */}
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
            <h2 className="text-base font-bold text-white">
              Live Spotlight: {liveMatch.teamA.name} vs {liveMatch.teamB.name}
            </h2>
          </div>
          <Link
            href={`/match/${liveMatch.id}`}
            className="text-xs text-emerald-400 hover:underline flex items-center gap-1 font-semibold"
          >
            <span>Live Match Center</span>
            <ArrowRight className="w-3 h-3" />
          </Link>
        </div>

        {/* Charts & Diagnostics Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-7">
            <WinProbabilityChart
              winProbability={liveMatch.winProbability}
              teamAName={liveMatch.teamA.name}
              teamBName={liveMatch.teamB.name}
              teamACode={liveMatch.teamA.code}
              teamBCode={liveMatch.teamB.code}
              innings={liveMatch.innings}
            />
          </div>

          <div className="lg:col-span-5">
            <AIAnalysisPanel
              analysis={liveMatch.aiAnalysis}
              teamAName={liveMatch.teamA.name}
              teamBName={liveMatch.teamB.name}
            />
          </div>
        </div>
      </div>

      {/* Head to Head Comparison Engine Card */}
      <div className="p-6 rounded-2xl bg-slate-900/70 border border-slate-800 space-y-4">
        <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
          <TrendingUp className="w-4 h-4 text-emerald-400" />
          <span>Historical Head-to-Head & Matchup Metrics</span>
        </h3>
        <p className="text-xs text-slate-400">
          Comparing recent head-to-head records between India and Pakistan in ICC multi-nation tournaments:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-center text-xs">
          <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-slate-500 text-[10px] uppercase font-bold block mb-1">India Wins</span>
            <span className="text-2xl font-black text-blue-400">8</span>
            <span className="text-[10px] text-slate-400 block mt-1">Last 10 meetings</span>
          </div>
          <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-slate-500 text-[10px] uppercase font-bold block mb-1">Pakistan Wins</span>
            <span className="text-2xl font-black text-emerald-400">2</span>
            <span className="text-[10px] text-slate-400 block mt-1">Last 10 meetings</span>
          </div>
          <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-slate-500 text-[10px] uppercase font-bold block mb-1">Avg 1st Innings Total</span>
            <span className="text-2xl font-black text-white">172</span>
            <span className="text-[10px] text-slate-400 block mt-1">Neutral venues</span>
          </div>
        </div>
      </div>

    </div>
  );
}
